Logger refactor
thelotter-enterprise/usergo pull request #6
Opened 2020-10-26 07:49 UTC by danielcNet-bet

This PR is not final , I am not going to merge it to main
Only for verifying that logger is Ok

2020-10-26 14:27 UTC, kolbis requested changes

2020-10-26 14:27 UTC, kolbis commented on core/logger2/logger.go
> +package logger2
when you merge change the package name to logger, logger_test

2020-10-26 14:27 UTC, kolbis commented on core/logger2/logger.go
> +// IsExpired  return true if day of logger.dateCreated and time.Now are not eq
documentation is not complete

2020-10-26 14:27 UTC, kolbis commented on core/logger2/logger.go
> +// Reload function create new log.Logger object
question: why is this needed?

2020-10-26 15:29 UTC, danielcNet-bet commented on core/logger2/logger.go
> +// Reload function create new log.Logger object
to verify if we need to create new file

2020-10-26 15:33 UTC, danielcNet-bet commented on core/logger2/logger.go
> +package logger2
as I wrote in PR comments
I am not going to merge it to main now , after completing review I am going to remove old logger and change implementation of logger in other packages and only after that -> merge to main

2020-10-31 16:34 UTC, kolbis approved these changes

2020-10-31 16:34 UTC, kolbis commented on core/logger2/logger.go
> +package logger2
when you merge to main make sure you rename the package.

2020-10-31 16:34 UTC, kolbis commented on core/logger2/logger.go
> +// Reload function create new log.Logger object
IsExpire is a bad name to indicate this.

2020-11-01 09:02 UTC, merged