Go client for cassandra db
thelotter-enterprise/usergo pull request #8
Opened 2020-10-30 15:28 UTC by mirceadthelotter

2020-10-31 17:22 UTC, kolbis requested changes

2020-10-31 17:22 UTC, kolbis commented on core/storage/cassandradb/client.go
> +package cassandradb
the documentations created do not match our standards.
first, you need to install vs code plugin:
go doc
Then it will warn you for bad documentations.
For example, each exported function you document, must start with the name of the function

2020-10-31 17:22 UTC, kolbis commented on core/storage/cassandradb/client.go
> +var CassandraSession *gocql.Session
suggest to have an interface type Cassandra with all the APIs you want to expose and then create struct that implements it.

type CassandraDB interface {
... all the functions
}

// implementation struct
type cassandradb struct {
}

// implement the functions as recievers
func (db cassandradb) Select(....) {
}

If you want to create a new Cassandra database:
func NewCassandraDB() CassandraDB {
// create a session here
}

2020-10-31 17:22 UTC, kolbis commented on core/storage/cassandradb/client.go
> +var CassandraSession *gocql.Session
using a global var to store the session, to my opinion is bad practice.

2020-10-31 17:22 UTC, kolbis commented on core/storage/cassandradb/client.go
> +func Select(cql string, consistencyLevel gocql.Consistency, params ...interface{}) ([]map[string]interface{}, error) {
all errors retuned from here should be wrapped as DBError

2020-10-31 17:22 UTC, kolbis commented on core/storage/cassandradb/client_test.go
> +package cassandradb_test
to my understanding this is integration test
you need to rename the file "cassandradb_integration_test"
you also need to decorate it with integration tests so that the build will not run it

2020-10-31 17:22 UTC, kolbis commented on core/storage/cassandradb/config.go
> +		KeyspaceName:     "golang_test",
this is used for tests. should not be here

2020-10-31 17:22 UTC, kolbis commented on core/storage/cassandradb/client_test.go
> +import (
Is there a proper way to unit test cassandra DB?

2020-11-02 16:35 UTC, mirceadthelotter commented on core/storage/cassandradb/client.go
> +package cassandradb
I installed go doc plugin but it doesn't show any helpful warning. I'm just getting a gogetdoc: no documentation found error.
Do you have any idea of what could be wrong?

2020-11-02 16:36 UTC, mirceadthelotter commented on core/storage/cassandradb/client.go
> +func Select(cql string, consistencyLevel gocql.Consistency, params ...interface{}) ([]map[string]interface{}, error) {
I didn't found any DBError so I created one and used it.

2020-11-02 16:37 UTC, mirceadthelotter commented on core/storage/cassandradb/client_test.go
> +import (
It's quite difficult because gocql driver does not use interfaces.
I found a workaround and I'm trying to use this approach: https://github.com/gocql/gocql/issues/415#issuecomment-277530829

2020-11-03 08:25 UTC, kolbis commented on core/storage/cassandradb/client.go
> +package cassandradb
no idea. Try to fix it
Still you need to follow the documentation concepts you see on other infra.

2020-11-03 08:26 UTC, kolbis commented on core/storage/cassandradb/client_test.go
> +import (
noted.
See if it make sense to get confidence in the implementation
If you feel there is little value due to the effort, ignore it.

2020-11-03 08:30 UTC, mirceadthelotter commented on core/storage/cassandradb/client.go
> +package cassandradb
do you run any command from command line to generate documentation or it just shows warnings when some documentation doesn't meet the standards?

2020-11-03 08:39 UTC, kolbis requested changes

2020-11-03 08:39 UTC, kolbis commented on core/storage/cassandradb/cassandradb.go
> +func NewCassandraDB(config Config, logger *tlelogger.Manager) CassandraDB {
you need to rebase from master. we no longer have logger manager

2020-11-03 08:39 UTC, kolbis commented on core/storage/cassandradb/cassandradb.go
> +		logDatabaseError(*db.Logger, err, "Error on CassandraDB -> Select -> iter.SliceMap()")
you will need to change the way you log
also, is there a reason you are using the "->" 
I think it should be a clear sentence

2020-11-03 08:39 UTC, kolbis commented on core/storage/cassandradb/cassandradb.go
> +	iter := db.Session.Query(cql, params...).Consistency(consistencyLevel).Iter()
need to handle case where session is nil

2020-11-03 08:39 UTC, kolbis commented on core/storage/cassandradb/cassandradb.go
> +	err := db.Session.Query(cql, params...).Consistency(consistencyLevel).Exec()
need to handle case where session is nil

2020-11-03 08:39 UTC, kolbis commented on core/storage/cassandradb/cassandradb.go
> +	if err := iter.Close(); err != nil {
should use defer!

2020-11-03 08:39 UTC, kolbis commented on core/storage/cassandradb/cassandradb.go
> +func (db *cassandradb) CloseSession() {
Question:
Is there a reason not to create a session for each query?
Is there a limit to the number of connections that can be opened from a session?
Is it important to close the session when the application ends? If so I would document it

2020-11-03 08:39 UTC, kolbis commented on core/storage/cassandradb/config.go
> +	ConsistencyLevel gocql.Consistency
consistency level is per query / command
what is the purpose of it in the context of the config?

2020-11-03 08:39 UTC, kolbis commented on core/storage/cassandradb/config.go
> +	Port int
there is an assumption here that all the hosts will listen on the same port.
Just make sure this is a proper assumption

2020-11-03 08:39 UTC, kolbis commented on core/storage/cassandradb/config.go
> +	}
Should not be here. It is not related to a production code.

2020-11-03 12:38 UTC, mirceadthelotter commented on core/storage/cassandradb/cassandradb.go
> +func NewCassandraDB(config Config, logger *tlelogger.Manager) CassandraDB {
I will integrate this PR to corego repo and rebase from there

2020-11-03 12:39 UTC, mirceadthelotter commented on core/storage/cassandradb/cassandradb.go
> +func (db *cassandradb) CloseSession() {
Opening a session it's an "expensive" operation and it is recommended to use a session per application or per keyspace.
Basically a session it's similar to a connection pool in sql

2020-11-03 12:39 UTC, mirceadthelotter commented on core/storage/cassandradb/config.go
> +	ConsistencyLevel gocql.Consistency
consistency level can bet set either per query/command either per session
doesn't make sense to set it in both session and query so I will leave it per query

2020-11-03 12:39 UTC, mirceadthelotter commented on core/storage/cassandradb/config.go
> +	Port int
if you have multiple hosts you can specify the port in  the hosts field like []string{"host1:123", "host2:124"}
I will remove Port config since it's confusing and you can set the port in hosts even if you have a single host

2020-11-03 14:35 UTC, closed without merging

2020-11-03 15:33 UTC, kolbis commented on core/storage/cassandradb/client.go
> +package cassandradb
Just show warning. Maybe @danielcNet-bet  can assist

2020-11-04 07:33 UTC, danielcNet-bet commented on core/storage/cassandradb/client.go
> +package cassandradb
Unfortunately , no. I just installed all packages that VScode proposed to me